
FROM 141502667606.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3

COPY code/requirements.txt /opt/ml/processing/requirements.txt

RUN pip install -r /opt/ml/processing/requirements.txt
